### ISSUE TITLE
Invoice production run checklist

### ISSUE THREAD

**Issue by dhruv-4** [dhruv-4/temp#2]
## Backup
- [x] backup booking with id: `61385aaa38ac640033f338a0`
```ts
db.getCollection('bookings').find({ "_id" : ObjectId("61385aaa38ac640033f338a0") })
```
- [x] backup invoices with ids: `6172793f8a290f0033654996`, `6172935e099cbb00336744f4`, `6172793f5ab17b00334f69b7`
```ts
db.getCollection('invoices').find({ "_id": { "$in": [ ObjectId("6172793f8a290f0033654996"), ObjectId("6172935e099cbb00336744f4"), ObjectId("6172793f5ab17b00334f69b7") ] } })
```
- [x] backup company with id: `604b68b599e62d00326b8340`
```ts
db.getCollection('companies').find({ "_id" : ObjectId("604b68b599e62d00326b8340") })
```
- [x] backup offer with id: `6137561238ac640033f20091`
```ts
db.getCollection('offers').find({ "_id" : ObjectId("6137561238ac640033f20091") })
```

## Run Lambda
- [x] Open lambda `l-invoice-collection-invoicing-prod`
- [x] Change configuration `DEBUG:*` for lambda, just to see logs
- [ ] Run lambda with
```ts
{
    "Records": [
      {
        "body": "{\"bookingId\":\"61385aaa38ac640033f338a0\",\"bookingItemId\":\"28c01247-4bbc-4c0b-b95a-9b8e29e30a23\",\"status\":\"anything\",\"version\":\"anything\"}"
      }
    ]
}
```

## Repeat after every lambda run
- [ ] Check invoice id of booking item before and after
- [ ] Check if invoice document has operational_data with new document storage id
- [ ] invoice_id in invoice document and booking_item.client_accounting_item.invoice_id should be same
- [ ] Check if document is available for download

## Run Lambda Again
- [ ] Run lambda with
```ts
{
    "Records": [
      {
        "body": "{\"bookingId\":\"61385aaa38ac640033f338a0\",\"bookingItemId\":\"baa38eac-204f-4afe-8b02-35b13c49128b\",\"status\":\"anything\",\"version\":\"anything\"}"
      }
    ]
}
```
- [ ] Run lambda with
```ts
{
    "Records": [
      {
        "body": "{\"bookingId\":\"61385aaa38ac640033f338a0\",\"bookingItemId\":\"84235397-314f-4df2-92ff-1c0129fbcd61\",\"status\":\"anything\",\"version\":\"anything\"}"
      }
    ]
}
```

**Comment by ushakow** [comment]
@dhruv-4 looks correct

**Comment by gabolop** [comment]
I'm not sure if this will work since I checked the invoice documents and they have operational data empty (no invoice number, and to be more precise it is missing `invoice_number_counter` and `invoice_number`) 

I had somewhere this list of things to do when something like this happened:

```

I. Booking 60d08a4b411bc50032714362

1. Increment the global invoice number counter in invoices
db.counters.findOneAndUpdate({id: 'operation_data_invoice_number_counter' }, {$inc: {'seq': 1} })

2.  Copy the_current_invoice number

3. Set the current invoice number as the invoice number of the booking 60d08a4b411bc50032714362 + 46c39efd-00ab-4ae5-ad75-24c98ca13967 booking item

db.invoices.findOneAndUpdate({booking_id: ObjectId('60d08a4b411bc50032714362'), booking_item_id: '46c39efd-00ab-4ae5-ad75-24c98ca13967'}, {$set: {'operational_data.invoice_number_counter': 1379, 'operational_data.invoice_number': 'B1379'} })

4. Check if it is set correctly
db.invoices.find({booking_id: ObjectId('60d08a4b411bc50032714362'), booking_item_id: '46c39efd-00ab-4ae5-ad75-24c98ca13967'})


5. Invoke https://eu-west-1.console.aws.amazon.com/lambda/home?region=eu-west-1#/functions/l-invoice-collection-invoicing-prod?tab=code with 
{
	"Records": [
	{
		"body":  {
			"bookingId": "60d08a4b411bc50032714362",
			"bookingItemId": "46c39efd-00ab-4ae5-ad75-24c98ca13967",
			"status": "invoiced",
			"version":  2
		}
	}
	]
}

6. Check pdf in "Invoices" for the item https://cockpit.comtravo.com/#/booking-detail/60d08a4b411bc50032714362 
```
